# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allprogramming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('video', models.TextField()),
                ('explain', models.TextField()),
                ('Programming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Allprogramming')),
            ],
        ),
        migrations.DeleteModel(
            name='Python',
        ),
    ]
