# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-26 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200125_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprogramming',
            name='img',
            field=models.ImageField(default='0', upload_to=''),
        ),
    ]
