# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allprogramming_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprogramming',
            name='img',
            field=models.TextField(default='0'),
        ),
    ]
