# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-27 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200126_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allprogramming',
            options={'verbose_name_plural': 'Allprogram'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='video',
        ),
        migrations.AddField(
            model_name='allprogramming',
            name='Allprog_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='lecture_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='Programming',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Allprogramming', verbose_name='Allprogram'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
