# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-27 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200127_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProgramming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_course', models.CharField(max_length=200)),
                ('sub_img', models.TextField()),
                ('sub_description', models.CharField(max_length=400)),
                ('subProg_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
