# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-27 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subprogramming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subprogramming',
            options={'verbose_name_plural': 'subProg'},
        ),
        migrations.RemoveField(
            model_name='subprogramming',
            name='subProg_slug',
        ),
        migrations.AddField(
            model_name='subprogramming',
            name='sub_programming',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Allprogramming', verbose_name='Allprogram'),
        ),
        migrations.AlterField(
            model_name='program',
            name='Programming',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.SubProgramming', verbose_name='subProg'),
        ),
    ]
