# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-30 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200130_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 19, 38, 40, 198579), verbose_name='Date Published'),
        ),
    ]
