# Generated by Django 3.0.2 on 2020-01-31 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200130_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprogramming',
            name='sub_slug',
            field=models.SlugField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 16, 2, 43, 411972), verbose_name='Date Published'),
        ),
    ]
