# Generated by Django 3.0.2 on 2020-01-31 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200131_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprogramming',
            name='sub_slug',
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 16, 9, 59, 794016), verbose_name='Date Published'),
        ),
    ]
